### ISSUE TITLE
要如何從DSP資料中心取得資料集

### ISSUE THREAD

**Issue by jerrywu2013** [dspim/a1-basic-data-analysis-course#1]
### 進行登入

http://ckan.nispc.tw/user/login
### 點選組織

http://ckan.nispc.tw/organization
### 挑選本次課程名稱，如:[A1]資料分析基礎班

http://ckan.nispc.tw/organization/a1course
### 挑選資料集，如:臺北市實價登錄租賃資料

http://ckan.nispc.tw/dataset/realestate-gis-a1

**Comment by wush978** [comment]
這看起來是要放在wiki，而不是放在issue

**Comment by wush978** [comment]
https://github.com/dspim/a1-basic-data-analysis-course/wiki/%E8%A6%81%E5%A6%82%E4%BD%95%E5%BE%9EDSP%E8%B3%87%E6%96%99%E4%B8%AD%E5%BF%83%E5%8F%96%E5%BE%97%E8%B3%87%E6%96%99%E9%9B%86
